#!/bin/bash
# v4
FOLDER_PATH="."
default_dec_ext=""

me="secrets-manager"

usage () {
  cat <<EOF
Usage:  $me -e [-p <password>] [-f <passfile>] [-x <decrypted-file-ext>] [-t <base-directory-path>]
        $me -d [-p <password>] [-f <passfile>] [-x <decrypted-file-ext>] [-t <base-directory-path>]

Gestion des secrets par le chiffrement ou le déchiffrement des fichiers dans les dossiers "secrets" d'un repo git

Options :
       *					Ce message d'aide
       -e	(Default)			Chiffre tous les fichiers dans les dossiers "secrets" avec l'extension ".enc".
       -d		                	Déchiffre tous les fichiers avec l'extension ".enc" dans les dossiers "secrets".
       -p                               	Spécifier un mot de passe directement en ligne de commande (sinon utilise un fichier de passe par défaut)
       -f	"./.secrets.pass" (Default)	Spécifier un fichier de passe (créé systématiquement)
       -x	".dec" (Default)		Extension des fichiers en sortie lors du déchiffrement. Par défaut ".dec".
       -t	"." (Default)			Dossier racine à partir duquel est appliqué le script. Par défaut le dossier courant.
       

EOF
}

while getopts edp:f:x:t: flag
do
  case "${flag}" in
    e) vact="enc";;
    d) vact="dec";;
    p) vpwd=${OPTARG};;
    f) vpp=${OPTARG};;
    x) vext=${OPTARG};;
    t) target=${OPTARG};;
    \?) echo "Invalid option: -"$OPTARG"" >&2
        usage
        exit 1;;
    : ) echo "Option -"$OPTARG" requires an argument." >&2
        usage
        exit 1;;
  esac
done

# Check if a file exists
check_file (){
  if [ -f $1 ]; then 
    echo "OK : "$(stat -c '%w' $1 | awk '{print $1" "$2}' | cut -d'.' -f1)", $1"
    return 0
  else
    echo "Erreur : (fichier introuvable) $1"
    return 1
  fi
}

# Create a passfile based on a given password or take the existing one
ensure_passfile (){
    if ! check_file $1; then
        echo "Création du fichier $1"
        PASSWORD=$2
        echo $PASSWORD > $1
        chmod 600 $1
    else
        PASSWORD=$(cat $1)
        if [ "$2" != "$PASSWORD" ]; then
          mv $1 $(dirname $1)$(date +"%Y%m%d%H%M%S")$(basename $1).bak
          echo $2 > $1
          chmod 600 $1
        fi
    fi
    # echo $PASSWORD
}

# Create a symbolic link for each secret file at the same location of its secrets directory
create_symlinks() {
find . -type f -iwholename "*/secrets/*" ! -name "$1" ! -name "*.enc" | xargs -I {} sh -c "dirname {} | xargs -I @ dirname @ | xargs -I % sh -c 'basename {} | xargs -I § ln -sf secrets/§ %'"
}

# Encrypt secrets
encrypt_secrets() {
if ! [ -z $3 ]; then ignore_dec="|${3}"; fi
for file in $(find "$FOLDER_PATH" -type f | grep -v /$ | grep -iE "vault|secrets/" | grep -iEv "template|\.enc${ignore_dec}")
do
    filename=$(basename "${file}")
    output=$(gpg -o "$file.enc" $1 $2 --symmetric --batch --yes --cipher-algo AES256 $file 2>&1)
    if ! [ $? -eq 0 ] || ! check_file "$file.enc"; then echo "$filename : $output"; fi
done
}

# Decrypt secrets
decrypt_secrets() {
for file in $(find "$FOLDER_PATH" -type f | grep -v /$ | grep -iE "\.enc" | grep -iE "vault|secrets/" | grep -iEv "template")
do
    filename=$(basename "${file::-4}")
    output=$(gpg -o "${file::-4}${3}" $1 $2 --batch --yes --decrypt $file 2>&1)
    if ! [ $? -eq 0 ] || ! check_file "${file::-4}${3}"; then echo "$file :"; echo $output; fi
done
}

# Main
FOLDER_PATH="${target:-${FOLDER_PATH}}"
dec_ext="${vext:-${default_dec_ext}}"
task="${vact:-enc}"
reponame=$(basename $(git remote get-url origin) | cut -d'.' -f1)
PASSPATH="${vpp:-./.${reponame}.secrets.pass}"
# Generate a random password
# number of character from 32 to 93
# Double quotes are removed
PWRD=$(echo "${vpwd:-$(date +%s | sha256sum | base64 | head -c 64 ; echo)}" | tr -d '"')

if ! [ -z $vpwd ]; then
  PASSWAY="--passphrase $PWRD"
else
  if check_file $PASSPATH > /dev/null 2>&1; then PWRD=$(cat $PASSPATH); fi
  PASSWAY="--passphrase-file $PASSPATH"
fi

ensure_passfile $PASSPATH $PWRD

case "$task" in
    "enc"|"encryption")
        encrypt_secrets $PASSWAY $dec_ext
        ;;
    "dec"|"decryption")
        decrypt_secrets $PASSWAY $dec_ext
        ;;
    *)
        echo "Invalid option : must encrypt or decrypt, cannot do none"
        usage
        exit 1
        ;;    
esac
create_symlinks $dec_ext
