networks:
  proxy:
    external: true
    name: proxy
services:
  reverse-proxy:
    networks:
      - proxy
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # container_name: ${ORG_NAME}_${STACK_NAME}_traefik
    environment:
      - TRAEFIK_LETSENCRYPT_EMAIL=${TRAEFIK_LETSENCRYPT_EMAIL:-hello@example.email}
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - '--api.insecure=true --providers.docker --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_LETSENCRYPT_EMAIL}'
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydashboard.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.mydashboard.service=api@internal
      - traefik.http.routers.mydashboard.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/srv/${ORG_NAME}/${STACK_NAME}/git/compose/traefik.yml:/etc/traefik/traefik.yml

